title: Murilo Fabricio
author: zemurilos
email: zemurilos@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A little about myself and my life :D.

# social links
github_username:  zemurilos

show_excerpts: false # true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minima
